import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";
import Navbar from "@/components/ui/navbar";
import WebsiteMounted from "@/lib/isMounted";
import { ThemeProvider } from "@/provider/theme-provider";

const interSans = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: "200",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${interSans.variable} antialiased text-[#fafafa] bg-[#0C0C0C] text-sm sm:text-base  max-h-svh`}
      >
        <WebsiteMounted>
          <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
            <div className="max-w-9xl mx-auto lg:px-11 px-6 pt-3">
              <Navbar />
              <main className="">
                  {children}
              </main>
            </div>
          </ThemeProvider>
        </WebsiteMounted>
      </body>
    </html>
  );
}
